version: "3.5"
services:
#  bolao.maxmat1.com.br:
#    container_name: bolao.maxmat1.com.br
#    build: .
#    image: node/bolao.maxmat1.com.br
#    user: "node"
#    environment:
#      - NODE_ENV=production
#      - PORT=8081
#      - CACHE_URL=cache.bolao.maxmat1.com.br
#      - CACHE_PORT=6379
#      - CACHE_PW=eYVX7EwVmmxKPC-DmwMtyKVge8oLd2t81
#    volumes:
#      - ./app-build:/usr/src/app
#      - ./process:/usr/src/process
#      - ./tmp:/tmp
#    ports:
#      - "5001:8081"
#    working_dir: /usr/src/app
#    restart: always
#    networks:
#        - rede-maxmat1

  cache.bolao.maxmat1.com.br:
    container_name: cache.bolao.maxmat1.com.br
    image: redis:7.2-alpine3.18
    restart: always
    ports:
      - '6399:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPC-DmwMtyKVge8oLd2t82
    volumes: 
      - ./cache-redis:/data
    networks:
        - rede-maxmat1

networks:
  rede-maxmat1:
    name: rede-maxmat1
    driver: bridge      