# renew_before_expiry = 30 days
version = 1.12.0
archive_dir = /etc/letsencrypt/archive/bolao.maxmat1.com.br
cert = /etc/letsencrypt/live/bolao.maxmat1.com.br/cert.pem
privkey = /etc/letsencrypt/live/bolao.maxmat1.com.br/privkey.pem
chain = /etc/letsencrypt/live/bolao.maxmat1.com.br/chain.pem
fullchain = /etc/letsencrypt/live/bolao.maxmat1.com.br/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = a52a4957612af51ef2ddaf84eafddf6a
authenticator = apache
installer = apache
server = https://acme-v02.api.letsencrypt.org/directory
